import { atom } from "recoil";

export const theProductState = atom({
  key: "theProductState",
  default: [
    {
      title: "Bajs",
      description: "Cescent 6vx",
      price: 8500,
      amount: 0,
      id: 0,
    },
    {
      title: "Cykel",
      description: "Cescent 6vx",
      price: 8500,
      amount: 0,
      id: 1,
    },
    {
      title: "Moped",
      description: "Puch Dakota",
      price: 2000,
      amount: 0,
      id: 2,
    },
    {
      title: "Scooter",
      description: "Yamaha KX3",
      price: 6500,
      amount: 0,
      id: 3,
    },
    {
      title: "Cykel",
      description: "Cescent 6vx",
      price: 8500,
      amount: 0,
      id: 4,
    },
    {
      title: "Moped",
      description: "Puch Dakota",
      price: 2000,
      amount: 0,
      id: 5,
    },
    {
      title: "Scooter",
      description: "Yamaha KX3",
      price: 6500,
      amount: 0,
      id: 6,
    },
    {
      title: "Cykel",
      description: "Cescent 6vx",
      price: 8500,
      amount: 0,
      id: 7,
    },
    {
      title: "Moped",
      description: "Puch Dakota",
      price: 2000,
      amount: 0,
      id: 8,
    },
    {
      title: "Scooter",
      description: "Yamaha KX3",
      price: 6500,
      amount: 0,
      id: 9,
    },
    {
      title: "Cykel",
      description: "Cescent 6vx",
      price: 8500,
      amount: 0,
      id: 10,
    },
    {
      title: "Moped",
      description: "Puch Dakota",
      price: 2000,
      amount: 0,
      id: 11,
    },
    {
      title: "Scooter",
      description: "Yamaha KX3",
      price: 6500,
      amount: 0,
      id: 12,
    },
    {
      title: "Cykel",
      description: "Cescent 6vx",
      price: 8500,
      amount: 0,
      id: 13,
    },
    {
      title: "Moped",
      description: "Puch Dakota",
      price: 2000,
      amount: 0,
      id: 14,
    },
    {
      title: "Scooter",
      description: "Yamaha KX3",
      price: 6500,
      amount: 0,
      id: 15,
    },
    {
      title: "Cykel",
      description: "Cescent 6vx",
      price: 8500,
      amount: 0,
      id: 16,
    },
    {
      title: "Moped",
      description: "Puch Dakota",
      price: 2000,
      amount: 0,
      id: 17,
    },
    {
      title: "Scooter",
      description: "Yamaha KX3",
      price: 6500,
      amount: 0,
      id: 18,
    },
    {
      title: "Cykel",
      description: "Cescent 6vx",
      price: 8500,
      amount: 0,
      id: 19,
    },
    {
      title: "Moped",
      description: "Puch Dakota",
      price: 2000,
      amount: 0,
      id: 20,
    },
    {
      title: "Scooter",
      description: "Yamaha KX3",
      price: 6500,
      amount: 0,
      id: 21,
    },
    {
      title: "Cykel",
      description: "Cescent 6vx",
      price: 8500,
      amount: 0,
      id: 22,
    },
    {
      title: "Moped",
      description: "Puch Dakota",
      price: 2000,
      amount: 0,
      id: 23,
    },
    {
      title: "Scooter",
      description: "Yamaha KX3",
      price: 6500,
      amount: 0,
      id: 24,
    },
  ],
});
